#We want to send a secret message through a packet channel by modifying the interpacket delays to encode 0s and 1s. 
#Here we use a delay between min and median to encode a 0 and median and max to encode a 1
#Set working directory
setwd("/Users/justine/Desktop/UC DAVIS/Spring18/Stats/Project")

#Read in the CSV
data <-read.table("Traffic_data_orig.csv",header=TRUE, sep = ',')

#Get the incoming packet times 
overt <- data$Time

#Get the interpacket delays of overt (Theres one less value because these are the differences)
difference <- c(500)
for(i in 1:500){
  difference[i] <- (overt[i+1] - overt[i])
}

#Convert secret message to bits (Piazza Post 169)
message <- "this is a secret message"
y <- charToRaw(message)
rawbits <- rawToBits(y)

#Calculate min,median,max
median <- median(difference)
min <- min(difference)
max <- max(difference)

covert <- c(overt) 

add <- 0
#2 to 192, generate delay for the duration of the secret message 
for( i in 2:(length(rawbits)+1)){
  if(rawbits[i] == 0){
    add <- runif(1, min, median)
    covert[i] = add + covert[i-1]
  }
  if(rawbits[i] == 1){
    add <- sample(median:max,1)
    covert[i] = add + covert[i-1]
  }
}

#193 - 501 This is the rest of the incoming packets 
covert[193] = covert[192] + difference[193]
for(i in 194:length(covert)){
  covert[i] = covert[i-1] + difference[i]
}
covert[501] = covert[500] + difference[500]

#difference2 is a vector of the inter-packet delays of covert
difference3 <- c(500)
for(i in 1:500){
  difference3[i] <- (covert[i+1] -  covert[i])
}
#Go from modified IPD -> bits and compare to rawbits (the raw converted message)
undo2 <- vector()
for(i in 1:192){
  if(difference3[i] > min && difference3[i] < median){
    undo2 <- append(undo2, 0)
  }else{
    undo2 <- append(undo2, 1)
  }
}
#Here we show the original message bit pattern and we also show the bit pattern generated by the covert IPDs. This demonstrates that our program to produce the modified IPDs sends the secret message correctly.
print(as.numeric(rawbits))
print(undo2)


hist(difference, xlab='Interpacket Delay Bin', ylab='Number of Packets', main = 'Overt')
hist(difference3, xlab='Interpacket Delay Bin', ylab='Number of Packets', main = 'Covert')