#We want to send a secret message through a packet channel by modifying the interpacket delays to encode 0s and 1s. 
#Here we use a delay between the min and mean to encode a 0 and between the mean and max to encode a 1

#Set working directory
setwd("/Users/justine/Desktop/UC DAVIS/Spring18/Stats/Project")

#Read in the CSV: This has the original interpacket delays 
data <-read.table("Traffic_data_orig.csv",header=TRUE, sep = ',')

#Get the incoming packet times 
overt <- data$Time

#Get the interpacket delays of overt (Theres one less value because these are the differences)
difference <- c(500)
for(i in 1:500){
  difference[i] <- (overt[i+1] - overt[i])
}

#Convert secret message to bits (Piazza Post 169)
message <- "this is a secret message"
y <- charToRaw(message)
rawbits <- rawToBits(y)

#Calculate min,mean,max
min <- min(difference)
max <- max(difference)
mean <- mean(difference)

covert <- c(overt) 

add <- 0
#2 to 192, generate delay for the duration of the secret message 
for( i in 2:(length(rawbits)+1)){
  if(rawbits[i] == 0){
    add <- runif(1, min, mean)
    covert[i] = add + covert[i-1]
  }
  if(rawbits[i] == 1){
    add <- sample(mean:max,1)
    covert[i] = add + covert[i-1]
  }
}

#193 - 501 This is the rest of the incoming packets 
covert[193] = covert[192] + difference[193]
for(i in 194:length(covert)){
  covert[i] = covert[i-1] + difference[i]
}
covert[501] = covert[500] + difference[500]

#difference2 is a vector of the inter-packet delays of covert
difference4 <- c(500)
for(i in 1:500){
  difference4[i] <- (covert[i+1] -  covert[i])
}
#Go from modified IPD -> bits and compare to rawbits (the raw converted message)
undo3 <- vector()
for(i in 1:192){
  if(difference4[i] > min && difference4[i] < median){
    undo3 <- append(undo3, 0)
  }else{
    undo3 <- append(undo3, 1)
  }
}

print("Histograms")
hist(difference, xlab='Interpacket Delay Bin', ylab='Number of Packets', main = 'Overt')
hist(difference4, xlab='Interpacket Delay Bin', ylab='Number of Packets', main = 'Covert')

print("qqplot using the original IPDs and the one's generated using the mean")
qqplot(difference, difference4)

#Here we show the original message bit pattern and we also show the bit pattern generated by the covert IPDs. This demonstrates that our program to produce the modified IPDs sends the secret message correctly.
print(as.numeric(rawbits))
print(undo3)
